### ISSUE TITLE
Wiki please

### ISSUE THREAD

**Issue by kindect** [imbushuo/PrimeG2Pkg#1]
As a programmer myself , I know how it feels like to add comment to my own code ,  not to mention wiki
But you should see that lots of people are using the HP prime G2 and it will be greatly helpful if you make a wiki or w more decent README

Best regards

**Comment by imbushuo** [comment]
This repo assumes you are familiar with EDK2. In fact, it incorporates with a modified U-Boot located at https://github.com/imbushuo/uboot for bootstrapping purposes.

To boot the UEFI, checkout the prinux repo and send the U-Boot and UEFI payload via SDP mode.
